### ISSUE TITLE
It fails to compile

### ISSUE THREAD

**Issue by markg85** [piotrjaromin/fast-xml2js#1]
Hi,

I'm happy you made this work for a comple of V8 releases, but it looks like there is a new compile failure.

Most notable, the following errors pop up:
```
../fast-xml2js.cpp:50:43: error: no matching function for call to 'v8::String::Utf8Length()'
   char *xml = new char[param1->Utf8Length() + 1];
```

and
```
../fast-xml2js.cpp:201:37: error: no matching function for call to 'v8::Function::Call(v8::Local<v8::Primitive>, const unsigned int&, v8::Local<v8::Value> [2])'
   cb->Call(Null(isolate), argc, argv);
```

Regarding the first one for Utf8Length, i did notice that last time as being deprecated. I guess it's gone now :)

Also, please be aware that there are a load of deprecated calls in this compile. Fixing this issue might make it work for a couple more V8 releases.. It might be worth looking into all the deprecated notices to get this package in a bit more stable condition.

Cheers,
Mark

**Comment by piotrjaromin** [comment]
Hi, sorry for long delay in answering, but newest version (1.4.1) should work, and all workings should be gone

**Comment by markg85** [comment]
Perhaps unsurprisingly, but i'm using [another](https://www.npmjs.com/package/xml2js) library now. I might switch back :)

Thank you for updating this library and this post!
